# Generated by Django 2.2.2 on 2019-07-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'catergories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=150)),
                ('stock', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='product_imgs')),
                ('best_seller', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete='MODEL.CASCADE', related_name='product', to='shop.Category')),
            ],
        ),
    ]
