# Generated by Django 2.2.1 on 2019-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('module', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('meta_keywords', models.CharField(max_length=150)),
                ('meta_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catergories',
                'db_table': 'categories',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=100)),
                ('old_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='img/product/main')),
                ('best_seller', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('category', models.ManyToManyField(to='shop.Category')),
            ],
        ),
    ]
