# Generated by Django 2.2.1 on 2019-06-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
    ]
