# Generated by Django 2.2.1 on 2019-06-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_category_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='available',
        ),
    ]
