# Generated by Django 2.2.3 on 2019-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('date_added', models.DateField()),
                ('product', models.ForeignKey(on_delete='model.CASCADE', to='shop.Product')),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ('-date_added',),
            },
        ),
    ]
